import { useCallback, useEffect, useMemo, useState } from "react";
import { BUILT_IN_VEHICLE_DB } from "./vehicles";
import { sanitizeVehicleDatabase } from "./validate";
import type { EvVehicle, VehicleDatabase } from "./types";

/**
 * Where the app looks for a refreshed vehicle database at runtime.
 *
 * This ships pointing at a same-origin static file (`public/vehicle-db.json`)
 * so the app works fully offline with zero configuration. That file is
 * regenerated by `npm run update-db` (see scripts/update-vehicle-db.mjs) and
 * can be wired into a scheduled CI job so the deployed app picks up fresher
 * specs without an app-store release. Point VITE_VEHICLE_DB_URL at any
 * externally-hosted JSON matching VehicleDatabase to pull from a live
 * source instead (e.g. a community EV-specs API, or a small backend that
 * runs the AI-assisted refresh workflow server-side).
 */
const REMOTE_DB_URL = import.meta.env.VITE_VEHICLE_DB_URL ?? `${import.meta.env.BASE_URL}vehicle-db.json`;

const CACHE_KEY = "ev-charge-estimator:vehicle-db-cache:v1";
const CACHE_CHECKED_KEY = "ev-charge-estimator:vehicle-db-checked-at:v1";

function loadCachedDb(): VehicleDatabase | null {
  try {
    const raw = window.localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    return sanitizeVehicleDatabase(JSON.parse(raw));
  } catch {
    return null;
  }
}

function saveCachedDb(db: VehicleDatabase) {
  try {
    window.localStorage.setItem(CACHE_KEY, JSON.stringify(db));
    window.localStorage.setItem(CACHE_CHECKED_KEY, new Date().toISOString());
  } catch {
    // Ignore storage failures (private browsing / quota).
  }
}

async function fetchRemoteDb(signal?: AbortSignal): Promise<VehicleDatabase> {
  const res = await fetch(REMOTE_DB_URL, { signal, cache: "no-cache" });
  if (!res.ok) throw new Error(`Vehicle DB fetch failed: HTTP ${res.status}`);
  const json = await res.json();
  const db = sanitizeVehicleDatabase(json);
  if (!db) throw new Error("Vehicle DB fetch returned malformed data");
  return db;
}

/** Merges the bundled built-in DB with a fetched/cached DB, remote entries taking priority by id. */
function mergeVehicleLists(remote: VehicleDatabase | null): EvVehicle[] {
  const byId = new Map<string, EvVehicle>();
  for (const v of BUILT_IN_VEHICLE_DB.vehicles) byId.set(v.id, v);
  if (remote) {
    for (const v of remote.vehicles) byId.set(v.id, v);
  }
  return Array.from(byId.values()).sort((a, b) => `${a.make} ${a.model}`.localeCompare(`${b.make} ${b.model}`));
}

export type VehicleDbStatus = "idle" | "checking" | "ready" | "error";

export interface VehicleDbState {
  vehicles: EvVehicle[];
  dbUpdatedAt: string;
  status: VehicleDbStatus;
  error: string | null;
  lastCheckedAt: string | null;
  refresh: () => void;
}

/**
 * Provides the merged vehicle list (built-in + any fresher cached/remote data),
 * and refreshes it in the background from REMOTE_DB_URL so new/updated vehicle
 * specs can reach users without an app update, as long as vehicle-db.json is
 * kept current (manually, via CI, or via an AI-assisted research pass — see
 * scripts/update-vehicle-db.mjs).
 */
export function useVehicleDatabase(): VehicleDbState {
  const [cachedRemote, setCachedRemote] = useState<VehicleDatabase | null>(() => loadCachedDb());
  const [status, setStatus] = useState<VehicleDbStatus>("idle");
  const [error, setError] = useState<string | null>(null);
  const [lastCheckedAt, setLastCheckedAt] = useState<string | null>(() => {
    try {
      return window.localStorage.getItem(CACHE_CHECKED_KEY);
    } catch {
      return null;
    }
  });
  const [refreshToken, setRefreshToken] = useState(0);

  useEffect(() => {
    const controller = new AbortController();
    setStatus("checking");
    setError(null);

    fetchRemoteDb(controller.signal)
      .then((db) => {
        if (controller.signal.aborted) return;
        const isNewer = !cachedRemote || db.updatedAt > cachedRemote.updatedAt || db.version !== cachedRemote.version;
        if (isNewer) {
          saveCachedDb(db);
          setCachedRemote(db);
        }
        setLastCheckedAt(new Date().toISOString());
        setStatus("ready");
      })
      .catch((err: unknown) => {
        if (controller.signal.aborted) return;
        // Not fatal: we still have the built-in DB (and any previously cached copy).
        setStatus("error");
        setError(err instanceof Error ? err.message : "Failed to check for vehicle database updates");
      });

    return () => controller.abort();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshToken]);

  const vehicles = useMemo(() => mergeVehicleLists(cachedRemote), [cachedRemote]);
  const dbUpdatedAt = cachedRemote && cachedRemote.updatedAt > BUILT_IN_VEHICLE_DB.updatedAt
    ? cachedRemote.updatedAt
    : BUILT_IN_VEHICLE_DB.updatedAt;

  const refresh = useCallback(() => setRefreshToken((t) => t + 1), []);

  return { vehicles, dbUpdatedAt, status, error, lastCheckedAt, refresh };
}
